mobs.spawn(AXOLOTL, pos(0, 0, 0))
player.teleport(pos(0, 0, 0))
mobs.spawn(AXOLOTL, pos(0, 0, 0))
blocks.place(WATER, pos(0, 0, 0))
blocks.place(GLASS, pos(1, 0, 0))
blocks.place(GLASS, pos(-1, 0, 0))
blocks.place(GLASS, pos(0, 1, 0))
blocks.place(GLASS, pos(0, -1, 0))
blocks.place(GLASS, pos(0, 0, 1))
blocks.place(GLASS, pos(0, 0, -1))
